### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by luantran1311** [Wiserobot-team/iOmniC#1]
I got this error when installing the extension, can you please check?

PHP Fatal error:  Default value for parameters with a class type can only be NULL in /chroot/home/aea75ef6/802f82dfa6.nxcli.net/html/vendor/wiserobot/module-iomnic/Api/OrderImportInterface.php on line 34
{"messages":{"error":[{"code":500,"message":"Fatal Error: 'Default value for parameters with a class type can only be NULL' in '\/chroot\/home\/aea75ef6\/802f82dfa6.nxcli.net\/html\/vendor\/wiserobot\/module-iomnic\/Api\/OrderImportInterface.php' on line 34","trace":"Trace is not available."}]}}

PHP 7.4
Magento 2.4.3-p1

**Comment by vietle208** [comment]
Hi,
Sorry for the late reply, can you please try removing the installed version then running the below command to install the compatible version?
composer require wiserobot/module-iomnic "^2.0"
